## Define the project name
export PROJECT_NAME := test

.PHONY: clean
.PHONY: up
.PHONY: down

## Define target objects to build for analysis
objects :=\
	data/greeting.rds\
	plots/example.pdf\
	tables/example.txt

## Default rule for make file
all: $(objects)

## Remove all files generated by make (listed in objects)
clean:
	rm -rf $(objects)

## Start project as an rstudio server in a docker container
### Generate random password & rename the .Rproj file
### Create .env file with project name and password
### echo password to terminal
### Build docker image and run container
up:
	$(eval PASSWORD := $(shell openssl rand -base64 15))
	@echo "PROJECT_NAME=$(value PROJECT_NAME)" > .env
	@echo "PASSWORD=$(value PASSWORD)" >> .env
	@echo Your password is $(value PASSWORD)
	docker-compose up -d --build

## Stop and remove docker container
down:
	docker-compose down

## Define rules for building objects ###############################
data/greeting.rds:\
	scripts/utils/sayHello.R\
	scripts/processing/makeGreeting.R
		mkdir -p data
		Rscript scripts/processing/makeGreeting.R

plots/example.pdf\
tables/example.txt:\
	scripts/utils/sayHello.R\
	data/greeting.rds\
	scripts/analysis/example.R
		mkdir -p plots tables
		Rscript scripts/analysis/example.R